name: 'slack_action'
description: 'Post to Slack'
branding:
  icon: 'bell'
  color: 'white'
inputs:
  webHook:
    description: 'slack webhook'
    required: true
  channel:
    description: 'channel'
    required: true
  job_status:
    description: 'success|failed|canceled'
    required: true
  message:
    description: 'message'
    required: false
  user_name:
    description: 'user name'
    required: false
  user_icon:
    description: 'user icon'
    required: false
  actions:
    description: 'actions'
    required: false
outputs:
  result:
    description: 'result'
runs:
  using: 'node20'
  main: 'dist/index.js'
