# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Action CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    NODE_OPTIONS: --openssl-legacy-provider
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tool3/ncc@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        src: 'index.js'
